---
- name: Ensure pve artefacts are setup
  hosts: proxmox_servers
  become: true

  tasks:
    - name: Remove the line with 127.0.1.1 entry
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^127\.0\.1\.1'

    - name: Add entry for pve host
      lineinfile:
        path: /etc/hosts
        insertafter: '^127\.0\.0\.1'
        line: "{{ ansible_default_ipv4.address}} {{ ansible_hostname }}.{{ lab_domain_name }} {{ ansible_hostname }}"

#    - name: setup /etc/network/interfaces
#      template:
#        src: templates/interfaces.j2
#        dest: /etc/network/interfaces
#        owner: root
#        group: root
#        mode: '0644'

    - name: Remove pve-enterprise repo
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        state: absent

    - name: Ensure proxmox gpg is setup
      ansible.builtin.get_url:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        dest: /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg
        mode: '0644'
        force: true

    - name: Ensure pve repo is setup
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
        state: present
        filename: pve-install-repo
